### ISSUE TITLE
Add SPDE smooth constructor?

### ISSUE THREAD

**Issue by dill** [dill/gamUtils#4]
[`smooth.construct.spde.smooth.spec`](https://github.com/dill/SPDE-smoothing/blob/master/supplementary/mgcv_spde_smooth.R) from our SPDE explainer paper might be useful BUT it would mean depending on R-INLA, which might be a headache.

**Comment by gavinsimpson** [comment]
If we only need a tiny bit from R-INLA then, assuming gamUtils has the correct licence (GPL) then we could just take what we want?

**Comment by dill** [comment]
That's an option. I think (but need to check) the code I need may 
involve some of the C++ backend so might get messy... I'll check when I 
have a moment.
