### ISSUE TITLE
Should this package have a different name?

### ISSUE THREAD

**Issue by dill** [dill/gamUtils#7]
What about `mgcvUtils` or `mgcvTools`? Good to avoid confusion that the tools would be general enough to work with other GAM implementations (some might but not all). Open to other suggestions too. I'm fairly sure you can't use `+` in a package name, otherwise I'd suggest `mgcv++` ;)

**Comment by eric-pedersen** [comment]
My vote's for mgcvUtils to avoid people thinking these will work for any GAM implementation.

**Comment by mfasiolo** [comment]
I thought I had already written something here (!?). Anyway, going for `mgcvUtils` or `mgcvTools` seems a good idea to me. We also have permission from Simon to use the `mgcv` "trademark"!

**Comment by dill** [comment]
👍  remember to change yr git configs :)
