### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by florianhartig** [dill/gamUtils#9]
Hey guys, related to https://github.com/florianhartig/DHARMa/issues/11, I wanted to ask: is this still active, and are you planning to push this to CRAN at some point?

For DHARMa, I will probably go with depending on mgcViz at the moment, but happy to switch if there is a stable / more generic alternative.

**Comment by dill** [comment]
Thanks for the ping Florian. I'm going to try to spend some time on this soon but in the meantime you should absolutely go ahead with `mgcViz` as the dependency.
